version: '3.8'

services:
  beluga-frontend:
    image: node:18-alpine
    container_name: beluga-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules # evita conflictos con los node_modules del host
    ports:
      - '5173:5173' # Vite dev server por defecto
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0